import { Inter } from 'next/font/google'
import Header from '@/components/header/header'
import Footer from '@/components/footer/footer'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'test quests',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className='bg-tq-black'>
			<body className={inter.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
