name: Run tests

on:
    pull_request:
        branches:
            - deployment
            - production
    workflow_dispatch:
    push:
        branches:
            - deployment
            - production
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /test/requirements.txt  # Adjust this based on your project's setup

    - name: Run Tests
      run: |
        pytest /test/tests # Adjust the path to your test directory

